### ISSUE TITLE
format is not defined

### ISSUE THREAD

**Issue by spinningsand** [Pauloo27/tiktok-live#13]
When I try `node index.js <username>` I get this:

```
C:\Users\CLUNKYBOXCOMPUTER\tiktok-live\index.js:21
if (format != 'mp4') {
^

ReferenceError: format is not defined
    at Object.<anonymous> (C:\Users\CLUNKYBOXCOMPUTER\tiktok-live\index.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Pauloo27** [comment]
Thanks! 
Should be fixed now

**Comment by spinningsand** [comment]
Thanks! It does work now.
