### ISSUE TITLE
Starts and stop downloading?

### ISSUE THREAD

**Issue by steve51184** [Pauloo27/tiktok-live#3]
So I have this installed correctly but when I run 

node index.js https://vm.tiktok.com/[removed]

It outputs the following:

URL > https://vm.tiktok.com/[removed]/
Found live "[removed]":
m3u8 URL: https://pull-hls-f11-va01.tiktokcdn.com/stage/stream-29933070622830665_or4.m3u8
flv URL: http://pull-flv-f11-va01.tiktokcdn.com/stage/stream-29933070622830665_or4.m3u8
Writing live to 7104045166184418054.flv. Press Ctrl C to STOP.

But it does all this in under 1-2 seconds and the .flv file it made is only 462 bytes and contains the following text:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:1654040968
#EXT-X-TARGETDURATION:3
#EXT-X-PROGRAM-DATE-TIME:2022-06-01T07:49:38+08:00
#EXTINF:2.240, no desc
stream-29933070622830665_or4-1654040968.ts
#EXT-X-PROGRAM-DATE-TIME:2022-06-01T07:49:40+08:00
#EXTINF:2.120, no desc
stream-29933070622830665_or4-1654040969.ts
#EXT-X-PROGRAM-DATE-TIME:2022-06-01T07:49:42+08:00
#EXTINF:2.040, no desc
stream-29933070622830665_or4-1654040970.ts

What's happening here?

Edit: it works if I run the command a second time but not the first time..

**Comment by Pauloo27** [comment]
can you please update and test it?

**Comment by steve51184** [comment]
Just updated but I get the error:

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/name/tiktok-live/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by steve51184** [comment]
Just updated but I get the same issue

**Comment by steve51184** [comment]
Confirmed working thank you

**Comment by Pauloo27** [comment]
Thank you for the report
